<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Adademics Rubric Meant for Seed Use Only
    |--------------------------------------------------------------------------
    */
    'campuses' => [
        [
            'title' => 'Plato University at Miami',
            'address' => '1320 S Dixie Hwy',
            'address_2' => '',
            'city' => 'Coral Gables',
            'postal' => '33146',
            'state' => 'FL',
            'country' => 'US',
            'timezone' => 'EST',
            'phone' => '',
            'desc' => '',
        ],
        [
            'title' => 'Plato University at New York',
            'address' => '70 Washington Square South',
            'address_2' => '',
            'city' => 'New York',
            'postal' => '10012',
            'state' => 'NY',
            'country' => 'US',
            'timezone' => 'EST',
            'phone' => '212-998-1212',
            'desc' => '',
        ],
        [
            'title' => 'Plato University at Salt Lake City',
            'address' => '201 Presidents Circle',
            'address_2' => 'Room 201',
            'city' => 'Salt Lake City',
            'postal' => '84112',
            'state' => 'UT',
            'country' => 'US',
            'timezone' => 'MST',
            'phone' => '801-581-7200',
            'desc' => '',
        ],
        [
            'title' => 'Plato University Online',
            'address' => '201 Presidents Circle',
            'address_2' => 'Room 201',
            'city' => 'Salt Lake City',
            'postal' => '84112',
            'state' => 'UT',
            'country' => 'US',
            'timezone' => 'MST',
            'phone' => '801-581-7200',
            'desc' => '',
        ],
    ],
    'buildings' => [
        'Erickson Hall',
        'Jefferson Hall',
        'Washington Hall',
        'Carter Hall',
        'Obama Hall',
        'Roosevelt Hall',
        'Cleveland Hall'
    ],
    'degrees' => [
		'Bachelor of Arts', 
		'Bachelor of Science', 
		'Bachelor of Fine Arts', 
		'Bachelor of General Studies'
    ],
    'colleges' => [
		'College of The Arts',
		'College of Arts and Sciences', 
		'College of Behavioral and Community Sciences', 
		'College of Business', 
		'College of Education', 
		'College of Engineering', 
		'College of Global Sustainability', 
		'College of Graduate Studies', 
		'Honors College', 
		'College of Marine Science', 
		'College of Medicine', 
		'College of Nursing', 
		'College of Pharmacy', 
		'College of Public Health'
    ],
    'majors' => [
		'Accounting', 
		'Advertising', 
		'Africana Studies',
		'Aging Sciences',
		'American Studies',
		'Anthropology', 
		'Applied Sciences', 
		'Art History', 
		'Behavioral Healthcare',
		'Biomedical Sciences',
		'Business Analytics and Information Systems',
		'Cell and Molecular Biology',
		'Chemical Engineering',
		'Chemistry',
		'Civil Engineering',
		'Classics-Latin/Greek',
		'Communication',
		'Communication Sciences and Disorders',
		'Computer Engineering',
		'Computer Science',
		'Criminology',
		'Dance',
		'Early Childhood Education: Pre Kindergarten/Primary',
		'Economics',
		'Electrical Engineering',
		'Elementary Education',
		'English',
		'English Education with ESOL Endorsement',
		'Environmental Biology',
		'Environmental Microbiology',
		'Environmental Science and Policy',
		'Exceptional Child Education with ESOL & Reading Endorsement',
		'Finance',
		'Foreign Language Education with ESOL Endorsement',
		'French',
		'General Business Administration',
		'General Studies',
		'Geography',
		'Geology',
		'German Studies',
		'Global Business',
		'Health Sciences',
		'History',
		'Humanities and Cultural Studies',
		'Industrial Engineering',
		'Information Studies',
		'Information Technology',
		'Integrative Animal Biology',
		'Interdisciplinary Classical Civilizations',
		'Interdisciplinary Natural Sciences',
		'Interdisciplinary Social Sciences',
		'International Studies',
		'Italian',
		'Long Term Care Administration',
		'Management',
		'Marine Biology',
		'Marketing',
		'Mass Communications',
		'Mathematics',
		'Mathematics Education',
		'Mechanical Engineering',
		'Medical Technology',
		'Microbiology',
		'Music Education',
		'Music Performance',
		'Music Studies',
		'Nusing: VCARE',
		'Nursing: RN to Bachelor\'s Sequence',
		'Nursing: Second Bachelor\'s Degree Sequence',
		'Nursing: Upper Division Sequence',
		'Philosophy',
		'Physical Education',
		'Physics',
		'Political Science',
		'Psychology',
		'Public Health',
		'Quantitative Economics and Econometrics',
		'Religious Studies',
		'Russian Studies',
		'Science Education',
		'Social Science Education',
		'Social Work',
		'Sociology',
		'Spanish',
		'Statistics',
		'Studio Art',
		'Theatre',
		'Women\'s and Gender Studies',
    ],
    'minors' => [
  		'Accounting and Business Analytics and Information Systems',
  		'Accounting and Economics',
  		'Accounting and Entrepreneurship',
  		'Accounting and Finance',
  		'Accounting and Management',
  		'Accounting and Marketing',
  		'Acoustic & Electronic Composition',
    	'Addictions and Behavioral Healthcare',
    	'Adult Community Services',
    	'Advertising',
    	'Aging and Behavioral Health',
    	'Aging Health Studies',
    	'Aging Health Studies and Health Information Technology',
    	'Aging Health Studies and Health Management',
    	'Anthropology',
    	'American Studies',
    	'Applied Behavior Analysis',
    	'Applied/Computational Mathematics',
    	'Asset Management',
    	'Ballet',
    	'Behavioral Healthcare',
    	'Behavioral Health Research',
    	'Biochemistry/Biotechnology',
    	'Biological Health Sciences',
    	'Biological Health Sciences and Aging Health Studies',
    	'Biological Health Sciences and Health Information Technology',
    	'Biological Health Sciences and Health Management',
    	'Biological Health Sciences and Social and Behavioral Health Sciences',
    	'Biology Education',
    	'Broadcast News',
    	'Broadcast-Program and Production',
    	'Business',
    	'Business Analytics and Information Systems',
    	'Business Analytics and Information Systems and Entrepreneurship',
    	'Children\'s Mental Health',
    	'Chemistry Education',
    	'Communication',
    	'Corporate Finance',
    	'Creative Writing',
    	'Criminal Justice',
    	'Criminology',
    	'Cybersecurity',
    	'Dance Studies',
    	'Data Science and Analytics',
    	'Deaf Studies',
    	'Design',
    	'Economics',
    	'Economics and Business Analytics and Information Systems',
    	'Economics and Entrepreneurship',
    	'Economics and Finance',
    	'Economics and Management',
    	'Economics and Marketing',
    	'Entrepreneurship',
    	'Environmental Policy & Management',
    	'Environmental Science and Policy',
    	'Exercise Science',
    	'Film and New Media Studies',
    	'Finance',
    	'Finance and Business Analytics and Information Systems',
    	'Finance and Entrepreneurship',
    	'Finance and Management',
    	'Finance and Marketing',
    	'French',
    	'General Geography',
    	'General Mathematics',
    	'German',
    	'Geography',
    	'Gerontology',
    	'Healthcare Business',
    	'Health Informatics',
    	'Health Information Technology',
    	'Health Management',
    	'Health Management and Health Information Technology',
    	'Human Geography',
    	'Humanities',
    	'Humanities and Cultural Studies',
    	'Identity and Community',
    	'Inequality and Social Justice',
    	'Information Science and Technology',
    	'Information Security',
    	'Information Studies',
    	'Information Studies: Information Architecture',
    	'Information Technology',
    	'Interpreter Training',
    	'International Studies',
    	'International Studies and Business',
    	'Italian',
    	'Jazz Studies',
    	'Journalism-Magazine',
    	'Journalism-News-Editorial',
    	'Language, Speech, and Hearing',
    	'Latin American, Caribbean, and Latino Studies',
    	'Leadership Studies',
    	'Literary Studies',
    	'Management',
    	'Management and Business Analytics and Information Systems',
    	'Management and Entrepreneurship',
    	'Management and Marketing',
    	'Marketing',
    	'Marketing and Business Analytics and Information Systems',
    	'Marketing and Entrepreneurship',
    	'Mass Communications',
    	'Middle School Mathematics',
    	'Middle School Science Education',
    	'Modern Dance',
    	'Multidisciplinary Behavioral Sciences',
    	'Performance',
		'Physics Education',
    	'Physical Geography',
    	'Political Science',
    	'Professional Writing, Rhetoric and Technology',
    	'Psychology',
    	'Public Administration',
    	'Public Health',
    	'Public Relations',
    	'Pure Mathematics',
    	'Religious Studies',
    	'Russian',
    	'Social and Behavioral Health Sciences',
    	'Social and Behavioral Health Sciences and Aging Health Studies',
    	'Social and Behavioral Health Sciences and Health Information Technology',
    	'Social and Behavioral Health Sciences and Health Management',
    	'Sociology',
    	'Spanish',
    	'Sport and Entertainment Management',
    	'Supply Chain Management',
    	'Theatre Arts',
    	'Urban Studies',
    	'Women\'s and Gender Studies',
    ],
    'subjects' => [
        'Accounting' => 'ACT',
        'Art' => 'ART',
        'Economics' => 'ECO',
        'English' => 'ENG',
        'Film' => 'FLM',
        'Geography' => 'GEO',
        'Government' => 'GOV',
        'Health' => 'HLT',
        'History' => 'HST',
        'Humanities' => 'HUM',
        'Languages' => 'LNG',
        'Management' => 'MGT',
        'Science' => 'SCI',
        'Sociology' => 'SCO',
    ],
    'tags' => [
        'English Authors',
        'Postmodernism',
        'Women\'s Issues',
        'Futurism',
        'Analytics',
        'Government',
        'Democracy',
        'Nature',
        'Conservation',
        'Gender Studies',
        'Native Americans',
        'Human Biology',
        'Exploration',
        'Cultural Issues',
        'Reproductive Rights',
        'Humanities',
        'Technology',
        'Languages',
    ],   
    'courses' => [
        [
            'subject_id' => 9,
            'level' => 1,
            'number' => 134,
            'title' => 'European Leadership',
            'sub_title' => 'Who\'s Who Among European Leadership',
            'online' => 1,
            'campus' => 1,
        ],
        [
            'subject_id' => 9,
            'level' => 1,
            'number' => 173,
            'title' => 'European History',
            'sub_title' => '',
            'online' => 1,
            'campus' => 0,
        ],
        [
            'subject_id' => 9,
            'level' => 2,
            'number' => 230,
            'title' => 'The Fall of Europe',
            'sub_title' => 'Things That Happened After Wars',
            'online' => 1,
            'campus' => 1,
        ],
        [
            'subject_id' => 9,
            'level' => 2,
            'number' => 270,
            'title' => 'Western History',
            'sub_title' => 'Europe & The West',
            'online' => 1,
            'campus' => 1,
        ],
        [
            'subject_id' => 9,
            'level' => 3,
            'number' => 350,
            'title' => 'Colonialism and Nationalism',
            'sub_title' => 'Lenses Through Which to View History',
            'online' => 1,
            'campus' => 1,
        ],
        [
            'subject_id' => 9,
            'level' => 4,
            'number' => 490,
            'title' => 'Learning From History',
            'sub_title' => 'How to Repeat What Works and Lose What Doesn\'t',
            'online' => 1,
            'campus' => 1,
        ],
    ], 
];